import {
  Home as HomeIcon,
  Database,
  FileImage,
  FileText,
  GitBranch,
  Server,
  Activity,
  FileJson,
  Rocket,
  Network,
  History,
  Globe,
  type LucideIcon,
} from "lucide-react";

export const TAB_ICONS: Record<string, LucideIcon> = {
  home: HomeIcon,
  dbdoc: Database,
  pumlviewer: FileImage,
  mdviewer: FileText,
  callflow: GitBranch,
  servermanager: Server,
  servermonitor: Activity,
  jsontool: FileJson,
  cicd: Rocket,
  netcheck: Network,
  githistory: History,
  apitester: Globe,
};
